server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /about {
        root /usr/share/nginx/html;
        try_files /about.html =404;
    }

    location /services {
        root /usr/share/nginx/html;
        try_files /services.html =404;
    }

    location /contact {
        root /usr/share/nginx/html;
        try_files /contact.html =404;
    }
}